# 🐳 CosmicLanding - Docker Compose
# Простое развертывание в продакшене

version: '3.8'

services:
  cosmiclanding:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmiclanding-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Обязательные переменные безопасности
      - JWT_SECRET=rSA4hfVLhhwa3u2dfgH8bwzbj7Q5SG9zGwnqeFLfFvYQZTYYdPnXu9cH9zqkLpks
      - ENCRYPTION_KEY=hQEhGj93DC4cQrnfbvmgYWG2WMKDqj93
      - COOKIE_SECRET=KCTe6jLdwJs9ChaBZc8XMJLqF7v5D8uZ
      - CSRF_SECRET=HmbmcNZ8g8sfhZGC8e6Vs3ESsx9Eh8ZpNAqUvjHWkT9ErcKwGr6HMkamMpdzBE4G
      - ALLOWED_ORIGINS=http://localhost:3000,https://thesim.in,https://www.thesim.in
    volumes:
      # Для персистентности данных (опционально)
      - ./data:/app/data
    networks:
      - cosmiclanding-network

  # Nginx отключен для локального тестирования
  # nginx:
  #   image: nginx:alpine
  #   container_name: cosmiclanding-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - cosmiclanding
  #   networks:
  #     - cosmiclanding-network

networks:
  cosmiclanding-network:
    driver: bridge

volumes:
  data:
